name: Test CI

on:
  push:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm lint
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check for failure labels
        uses: RandellDawson/fail-with-these-labels-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-to-fail: 'status: blocked,status: i18n review required'
